swagger: '2.0'
info:
  description: >-
    This component provides function to work with Product / Image informations:
    - Create, update and delete products
    - Create, update and delete images
    - Get images from a product
  version: 1.0.0
  title: 'Product API'
  contact:
    email: rmzoni@gmail.com
  license:
    name: GNU 3.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:4000'
basePath: /products/v1
tags:
  - name: product
    description: Product resource
  - name: product_association
    description: The product association link
  - name: image
    description: Image resource
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /products:
    get:
      tags:
        - product
      summary: Return all products
      description: Return all products
      operationId: getProducts
      parameters:
        - name: expand
          in: query
          type: string
          required: false
          description: If you want to exapand some child relatioships you must use this atribute for images and child products.
      responses:
        '200':
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/DefaultException'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/DefaultException'
        '422':
          description: Semantic Error
          schema:
            $ref: '#/definitions/DefaultException'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/DefaultException'
    post:
      tags:
        - product
      summary: Create a new product
      description: >-
        This operation create a new product. So, does not provide the identifier because this is going to be generates automatic for you.
        This operation does not apply association for products and images. Please, see the correct methods to apply association for images and products.
      operationId: createProduct
      parameters:
        - name: body
          in: body
          description: The product type to be created
          schema:
            $ref: '#/definitions/Product'
      responses:
        '201':
          description: Successful operation and the created product with its identifier
          schema:
            $ref: '#/definitions/Product'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/DefaultException'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/DefaultException'
        '422':
          description: Semantic Error
          schema:
            $ref: '#/definitions/DefaultException'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/DefaultException'

  /products/{product_id}:
    get:
      tags:
        - product
      summary: Return a product by its identifier
      description: Return a product by its identifier
      operationId: getProductById
      parameters:
        - name: product_id
          in: path
          description: Product Identifier
          required: true
          type: integer
        - name: expand
          in: query
          type: string
          required: false
          description: If you want to exapand some child relatioships you must use this atribute for images and child products.
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Product'
        '204':
          description: No Product Found
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/DefaultException'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/DefaultException'
        '422':
          description: Semantic Error
          schema:
            $ref: '#/definitions/DefaultException'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/DefaultException'
    put:
      tags:
        - product
      summary: Update a product by its identifier
      description: >-
        This operation update a existing product.
        This operation does not apply association for products and images. Please, see the correct methods to apply association for images and products.
      operationId: udpateProductById
      parameters:
        - name: product_id
          in: path
          description: Product Identifier
          required: true
          type: integer
        - name: body
          in: body
          description: The product type to be update
          schema:
            $ref: '#/definitions/Product'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Product'
        '204':
          description: No Product Found
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/DefaultException'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/DefaultException'
        '422':
          description: Semantic Error
          schema:
            $ref: '#/definitions/DefaultException'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/DefaultException'
    delete:
      tags:
        - product
      summary: Delete a product by its identifier
      description: >-
        Delete a product by its identifier.
        This is going to remove all child products and images.
      operationId: deleteProductById
      parameters:
        - name: product_id
          in: path
          description: Product Identifier
          required: true
          type: integer
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/DefaultException'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/DefaultException'
        '422':
          description: Semantic Error
          schema:
            $ref: '#/definitions/DefaultException'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/DefaultException'

  /products/{product_id}/images:
    post:
      tags:
        - image
      summary: Create a new image and associated with product
      description: >-
        This operation creates a new image and associated with the current product.
      operationId: createProductImage
      parameters:
        - name: product_id
          in: path
          description: Product Identifier
          required: true
          type: integer
        - name: body
          in: body
          description: The image to be created
          schema:
            $ref: '#/definitions/Image'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Image'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/DefaultException'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/DefaultException'
        '422':
          description: Semantic Error
          schema:
            $ref: '#/definitions/DefaultException'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/DefaultException'
    get:
      tags:
        - image
      summary: Return all images from a product
      description: Return all images from a product
      operationId: getImagesByProduct
      parameters:
        - name: product_id
          in: path
          description: Product Identifier
          required: true
          type: integer
        - name: expand
          in: query
          type: string
          required: false
          description: If you want to exapand some child relatioships you must use this atribute for images and child products.
      responses:
        '200':
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Image'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/DefaultException'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/DefaultException'
        '422':
          description: Semantic Error
          schema:
            $ref: '#/definitions/DefaultException'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/DefaultException'

  /products/{product_id}/images/{image_id}:
    delete:
      tags:
        - image
      summary: Delete a product image by its identifier
      description: >-
        Delete a product image by its identifier.
      operationId: deleteImageById
      parameters:
        - name: product_id
          in: path
          description: Product Identifier
          required: true
          type: integer
        - name: image_id
          in: path
          description: Product Identifier
          required: true
          type: integer
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/DefaultException'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/DefaultException'
        '422':
          description: Semantic Error
          schema:
            $ref: '#/definitions/DefaultException'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/DefaultException'


  /products/{product_id}/products_associations/{product_association_id}:
    put:
      tags:
        - product_association
      summary: Update the product association.
      description: >-
        Update the product association creating a link between the father product (product_id) and the child product (product_association_id)
      operationId: updateProductAssociation
      parameters:
        - name: product_id
          in: path
          description: Product Identifier
          required: true
          type: integer
        - name: product_association_id
          in: path
          description: Product Association Identifier
          required: true
          type: integer
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/DefaultException'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/DefaultException'
        '422':
          description: Semantic Error
          schema:
            $ref: '#/definitions/DefaultException'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/DefaultException'
    delete:
      tags:
        - product_association
      summary: Delete the product association.
      description: >-
        Remove the product association between the father product (product_id) and the child product (product_association_id)
      operationId: deleteProductAssociation
      parameters:
        - name: product_id
          in: path
          description: Product Identifier
          required: true
          type: integer
        - name: product_association_id
          in: path
          description: Product Association Identifier
          required: true
          type: integer
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/DefaultException'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/DefaultException'
        '422':
          description: Semantic Error
          schema:
            $ref: '#/definitions/DefaultException'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/DefaultException'

definitions:
  DefaultException:
    type: object
    description: >-
        Default Exception Type. This structure is used for most of HTTP Returned Status Codes:
          - 4xx
          - 5xx
    properties:
      message:
        type: string
        description: Error message
        example: Resource not found
  Image:
    type: object
    properties:
      id:
        type: integer
        description: The image identifier
        example: 1
      type:
        type: string
        description: The image type
        example: main
    required:
      - type
    example:
      id: 1
      type: main
  Product:
    type: object
    properties:
      id:
        type: integer
        description: The product identifier
        example: 1
      name:
        type: string
        description: The name of the product
        example: Game of Thrones
      description:
        type: string
        description: The description of the product
        example: >-
          From a master of contemporary fantasy comes the first novel of a landmark series unlike any you’ve ever read before.
          With A Game of Thrones, George R. R. Martin has launched a genuine masterpiece, bringing together the best the genre has to offer.
          Mystery, intrigue, romance, and adventure fill the pages of this magnificent saga, the first volume in an epic series sure to delight fantasy fans everywhere.
      images:
        type: array
        items:
          $ref: "#/definitions/Image"
        description: The images that belong to this product
        example:
          - id: 1
            type: main
          - id: 1
            type: back
      products:
        type: array
        items:
          $ref: "#/definitions/Product"
        description: Childs products related to this product
        example:
          - id: 1
            name: Game of Thrones
            description: From a master of contemporary fantasy comes the first novel of a landmark series unlike any you’ve ever read before.
            images:
              - id: 1
                type: main
    required:
      - name
      - description
    example:
      id: 1
      name: Game of Thrones
      description: From a master of contemporary fantasy comes the first novel of a landmark series unlike any you’ve ever read before.
      images:
        - id: 1
          type: main
